name: Publish Docker image
on:
  release:
    types: [published]
jobs:
  push_to_registries:
    name: Push Docker image to multiple registries
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2      
        env:
            VUE_APP_BASE_URL: ${{ secrets.UI_HOST }}
            VUE_APP_PAKKET_SERVICE_PROXY: ${{ SECRETS.PAKKETSERVICE_HOST }}
          
      - name: Push to Docker Hub
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: fipost/ui
          tag_with_ref: true
