on:
  push:
    branches: [ developer ]
    
name: Test
jobs:
  push_to_registries:
    name: Push Docker image to multiple registries
    runs-on: ubuntu-latest
    steps:
    
      - run: |
          echo ${{ secrets.APP_URL }}
