on:
  push:
    branches: [ master ]
  pull_request:
    types: [opened, synchronize, reopened]
    
name: Publish Docker image
jobs:
  push_to_registries:
    name: Push Docker image to multiple registries
    runs-on: ubuntu-latest
    steps:
    
      - run: |
          echo ${{ secrets.APP_URL }}
